### PR TITLE
user.roles after v2.0

### PR DESCRIPTION
**Pull request by ashishapy**
user.roles is not a function(…) error, when Meteor.user().roles() used after migration to v2.0.

Use Meteor.user().roles instead.

### CODE REVIEW

**Comment by nicolaslopezj** [comment]
Thanks
